spring:
  application.name: Project
  devtools:
    restart:
      enabled: true
  datasource:
    # url: jdbc:postgresql://localhost:5432/project
    url: jdbc:postgresql://3.38.9.29:5432/traivel
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: 3.38.9.29
      port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.project.entity

#  configuration:
#    map-underscore-to-camel-case: true
#  config-location: classpath:mybatis-config.xml
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

aws:
  access-key: ${AMAZON_ACCESS_KEY}
  secret-key: ${AMAZON_SECRET_ACCESS_KEY}
  region: ap-northeast-2
  s3:
    bucket: ${AWS_S3_BUCKET}

